name: deepobs
dependencies:
  - pip
  - python
  - tensorflow-gpu
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::black
  - conda-forge::flake8
  - conda-forge::flake8-bugbear
  - conda-forge::flake8-comprehensions
  - conda-forge::isort
  - conda-forge::palettable
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::m2r2
  - conda-forge::sphinx
  - conda-forge::sphinx-automodapi
  - conda-forge::sphinx_rtd_theme
  - pip:
    - graphviz
    - pre-commit
    - -e .
