name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - development
      - master


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install torch
          pip install torchvision
          pip install tensorflow
          pip install .
      - name: Run pytest
        run: |
          make test-light
